apiVersion: v1
data:
  config.yaml: |
    "forgot_password_text": "Contact your admin"
    "legal_urls":
      "privacy_policy": "https://www.triology.de/"
      "terms_of_service": "https://docs.cloudogu.com/"
      "imprint": "https://cloudogu.com/"
    ldap:
      attribute_fullname: cn
      attribute_group: memberOf
      attribute_id: uid
      attribute_mail: mail
      ds_type: embedded
      host: ldap
      port: "389"
      search_filter: (objectClass=person)
    oidc:
      "enabled": "true"
      "discovery_uri": "http://${ecoSystem.externalIP}:9000/auth/realms/Test/.well-known/openid-configuration"
      "client_id": "cas"
      "display_name": "cas"
      "optional": "true"
      "scopes": "openid email profile groups"
      "allowed_groups": "testers"
      "attribute_mapping": "email:mail,family_name:surname,given_name:givenName,preferred_username:username,name:displayName,groups:externalGroups"
kind: ConfigMap
metadata:
  labels:
    app: ces
    dogu.name: cas
    k8s.cloudogu.com/type: dogu-config
  name: cas-config
  namespace: ecosystem