services:
  keycloak:
    container_name: kc
    image: quay.io/keycloak/keycloak:24.0
    command: ["start-dev", "--http-port=8080", "--hostname-strict=false"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
