version: "2"
services:
  ldap:
    image: cloudogu/sample-ldap:0.1.0
    ports:
    - "1389:389"
  etcd:
    image: quay.io/coreos/etcd:v2.3.8
    command: ["-bind-addr", "0.0.0.0:4001"]
    ports:
      - "4001:4001"
      - "2379:2379"