version: "2"
services:
  ldap:
    image: cloudogu/sample-ldap:0.2.0
    ports:
      - "1389:389"
  etcd:
    image: quay.io/coreos/etcd:v3.2.32
    command: ["etcd","--listen-client-urls", "http://0.0.0.0:4001", "--advertise-client-urls", "http://0.0.0.0:4001"]
    ports:
      - "4001:4001"
      - "2379:2379"
