apiVersion: v2
name: cas
description: A Helm chart for CAS, the LOP's single sign-on provider.

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application
version: 0.0.0-replaceme
appVersion: "0.0.0-replaceme"

annotations:
  # we need the -0 as otherwise we cannot depend on (and therefore test) pre-release versions
  "k8s.cloudogu.com/ces-dependency/k8s-auth-registration-operator": ">=0.0.1-0"