server.port=8080
cas.server.name=http://localhost:8080
cas.server.prefix=${cas.server.name}/cas

logging.config=file:/etc/cas/config/log4j2.xml

# cas.authn.accept.users=
cas.service-registry.watcher-enabled=true

# Auto-initialize the registry from default JSON service definitions
cas.service-registry.json.location=file:/etc/cas/config/services

cas.authn.accept.users=admin::admin123
cas.authn.attributeRepository.stub.attributes.mail=admin@properties.local
cas.authn.attributeRepository.stub.attributes.cn=Admin
cas.authn.attributeRepository.stub.attributes.givenName=Adam
cas.authn.attributeRepository.stub.attributes.surname=Strator
cas.authn.attributeRepository.stub.attributes.groups=adminGr
