apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    {{ include "cas.labels" . | nindent 4 }}
  name: {{ include "cas.name" . }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - http:
        paths:
          - backend:
              service:
                name: {{ include "cas.name" . }}
                port:
                  name: {{ .Values.service.port.name }}
            path: /{{ include "cas.name" . }}
            pathType: Prefix