apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cas.fullname" . }}
  labels:
    {{- include "cas.labels" . | nindent 4 }}
    {{- include "cas.backupLabels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.minVolumeSize }}
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
